# aws cloudformation create-stack --stack-name "build-stack" --template-body file://codebuild.template.yaml --capabilities CAPABILITY_IAM
# aws cloudformation deploy --stack-name "build-stack" --template-file codebuild.template.yaml --capabilities CAPABILITY_IAM --parameter-overrides "GitHubURL=$GITHUB_URL"
Description: CodeBuild project for piggybank

Parameters:
  NetworkStackName:
      Type: String
      Default: "network-stack"
  GitHubURL:
      Type: String

Resources:
  BuildBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'

  # Build
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:4.0"
        EnvironmentVariables:
          - Name: QUARKUS_PROFILE
            Value: prod
            Type: PLAINTEXT
          - Name: ARTIFACTS_S3_BUCKET
            Value: !Ref BuildBucket
            Type: PLAINTEXT
      Source:
        Type: GITHUB
        Location: !Ref GitHubURL
      TimeoutInMinutes: 15
      VpcConfig:
        VpcId:
          Fn::ImportValue:
            !Sub "${NetworkStackName}-VPC"
        Subnets:
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-PrivateSubnet0"
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-PrivateSubnet1"
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-PrivateSubnet2"
        SecurityGroupIds: [!Ref CodeBuildSecurityGroup]
      Cache:
        Type: S3
        Location: !Sub "${BuildBucket}/cache"

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 's3:*'
                  - 'logs:*'
                  - 'ec2:*'
                Effect: Allow
                Resource: '*'
  CodeBuildSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Codebuild Internet Group
      GroupDescription: 'CodeBuild SecurityGroup'
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VPC"

Outputs:
  CodeBuildProjectName:
    Description: Code Build Name
    Value: !Ref CodeBuildProject

  BuildBucketName:
    Description: Build Bucket Name
    Value: !Ref BuildBucket