# aws cloudformation create-stack --stack-name "database-stack" --template-body file://database.template.yaml
Description: Database stack

Parameters:
  NetworkStackName:
    Type: String
    Default: "network-stack"

  MasterUsername:
    Type: String
    Default: "root"

  MasterUserPassword:
    Type: String
    Default: "Masterkey123"

  DBName:
    Type: String
    Default: "piggybankdb"

Resources:
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Database"
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VPC"
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-DatabaseSecurityGroup'

  DatabaseIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref 'DatabaseSecurityGroup'
      IpProtocol: 'tcp'
      FromPort: '3306'
      ToPort: '3306'
      CidrIp: '0.0.0.0/0'


  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet Group for RDS
      SubnetIds:
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-PrivateSubnet0"
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-PrivateSubnet1"
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-PrivateSubnet2"

  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineMode: serverless
      MasterUsername: !Ref "MasterUsername"
      MasterUserPassword: !Ref "MasterUserPassword"
      DBSubnetGroupName: !Ref "DatabaseSubnetGroup"
      DatabaseName: !Ref "DBName"
      EnableHttpEndpoint: true
      VpcSecurityGroupIds:
        - !Ref "DatabaseSecurityGroup"

#  DatabasePrimaryInstance:
#    Type: AWS::RDS::DBInstance
#    Properties:
#      Engine: aurora-mysql
#      DBClusterIdentifier: !Ref "DatabaseCluster"
#      DBInstanceClass: !Ref "DBInstanceClass"
#      DBSubnetGroupName: !Ref "DatabaseSubnetGroup"
#     PubliclyAccessible: true

Outputs:

  PiggybankRDS:
    Description:   PiggybankRDS
    Value: !Ref DatabaseCluster

  DbEndpoint:
    Description:   Piggybank Address
    Value: !GetAtt DatabaseCluster.Endpoint.Address

  PiggybankRDSSecurityGroup:
    Description:   PiggybankRDS Security Group
    Value: !Ref DatabaseSecurityGroup

